### ISSUE TITLE
Functionality documentation: functions renamed without documentation

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#11]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

In README.md, "Most functions were renamed and inputs have changed to make them more intuitive and easier to use."

Many users of TMD 2.5 do not use the functions as standalone functions; rather, they are called by other tools to perform tasks such as preparing tidal inputs for circulation models. Before incorporating TMD 3.0 into their processing pipeline, the large user base of TMD (mentioned in your paper) will have to spend significant time searching through the documentation and source code to determine: what actually changed (incl. any bug fixes), what was just renamed, and what has subtly different outputs (such as cm/s vs. m/s, terminology "Depth" vs. "Elevation" vs. "Z" vs. "zi" vs. "z" vs. "TS" vs. 'h', "amp" vs. '*Am'). For example, I can get same thing using:

```
% TMD 2.5
filename = '/Users/lnferris/MD_Matlab_Toolbox_v2.5-master/TMD/DATA/Model_tpxo7.2';
[TS,~]=tmd_tide_pred(filename,time,lat,lon,'z',[]);

% TMD 3.0
filename = '/Users/lnferris/TPXO9_atlas_v5.nc';
z = tmd_predict(filename,lat,lon,time,'h');

figure
plot(time,z)
hold on
plot(time,TS)
```
I want the authors to create a chart (or other medium of their choice) that outlines which TMD 2.5 functions have direct proxies to TMD 3.0, which functions were slightly-but-critically changed, and which functions are completely novel. The purpose of this is to minimize confusion as people adopt the new version.

**Comment by chadagreene** [comment]
I'm embarrassed we didn't think of this before. We've now added a page that describes what's new in TMD3.0, including the suggested table: https://github.com/chadagreene/Tide-Model-Driver/blob/main/doc/whats_new.md#converting-from-previous-tmd-releases

**Comment by lnferris** [comment]
I think the proxy of tmd_interp is tmd_extract_HC

**Comment by chadagreene** [comment]
Yes, of course, thank you! Fixed.

**Comment by lnferris** [comment]
Awesome. 

Also I think Conlist is an output of tmd_tide_pred and tmd_extract_HC in TMD 2.5 (so those are sort of the clunky TMD 2.5 proxy of conlist?). It is nice that TMD 3.0 spits it out directly. You could say "output of `tmd_tide_pred` and `tmd_extract_HC`" in the conlist "previous name" box if you wanted.
