### ISSUE TITLE
Automated Tests: tide_model_intercomparison.md

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#15]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018) and related to [Issue 11](https://github.com/chadagreene/Tide-Model-Driver/issues/11)

It would be nice to also include a test(s) comparing timeseries produced using the TMD 2.5 vs. TMD 3.0 functions. I don't think these tests needs to be automated; a code block would be fine.

**Comment by chadagreene** [comment]
Nice idea. We've now added a page that describes updates in TMD3.0 compared to previous versions, in which we point users to a script they may use to compare results: https://github.com/chadagreene/Tide-Model-Driver/blob/main/doc/whats_new.md
