### ISSUE TITLE
unexpected behavior: tmd_interp and tmd_data

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#17]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

There are two issues here: the toolbox seems to have inconsistent longitudinal range handling (whether -180/180 or 0/360 is fine), and the inability to interpolate data in a region which should be available.  (If I am misunderstanding the usage of tmd_interp and this is producing the latter problem, please let me know.)

Function tmd_interp seems to work for TPXO but not Arc2km

```
filename = '/Users/lnferris/Desktop/TPXO9_atlas_v5.nc';
%filename = '/Users/lnferris/Desktop/Arc2kmTM_v1.nc';

latq = linspace(70,72,60*2);
lonq = linspace(-66,-62,60*4);
[loni,lati] = meshgrid(lonq,latq); 
zi = tmd_interp(filename,variable,loni,lati);
```
and produces the following error for Arc2km:

```
Error using tmd_data
No tide data available in the region of interest.

Error in tmd_interp (line 160)
      [z,x,y] = tmd_data(filename,variable,'bounds',[xi(:) yi(:)],varargin{:});

Error in check_TBD (line 83)
zi = tmd_interp(filename,variable,loni,lati);

```
I tried to use tmd_data to confirm the data exists...

```
conid = 3;
variable = 'hRe';
[Z,lon,lat] = tmd_data(filename,variable,'geo');
ocean = tmd_data(filename,'mask'); 
data = Z(:,:,conid);
data(~ocean) = NaN; 

figure
pcolor(lon,lat,data);
shading flat
hold on
xline(-66); xline(-62); yline(70); yline(72)  
xlim([-80 -50]); ylim([60 80])
```
and got this strange result for Arc2km (e.g. what are the stripes/continuities?):

<img width="599" alt="Screen Shot 2023-12-21 at 2 53 10 PM" src="https://github.com/chadagreene/Tide-Model-Driver/assets/24570061/224f93dc-a5e2-4eee-a05d-b480751650a5">

and this for TPXO (no negative longitude handling):

<img width="876" alt="Screen Shot 2023-12-21 at 3 02 07 PM" src="https://github.com/chadagreene/Tide-Model-Driver/assets/24570061/8373b78c-6397-4761-b362-124802cd755d">

**Comment by chadagreene** [comment]
Whoa, @lnferris thanks for conducting such a close examination of the function behavior using multiple different models. This kind of test really helps us identify unexpected behavior and understand how users are using the functions. 

You've identified two issues here: 

### 1. Function `tmd_interp` seems to work for TPXO but not Arc2km

Thanks for providing a minimal working example--It just looks like you've swapped the order of lat and lon in `tmd_interp`. Here's a comparison of the two models using your lat,lon grid: 
```matlab 
latq = linspace(70,72,60*2);
lonq = linspace(-66,-62,60*4);
[loni,lati] = meshgrid(lonq,latq); 

zi_tpx = tmd_interp('TPXO9_atlas_v5.nc','hAm',lati,loni,'con','m2');
zi_arc = tmd_interp('Arc2kmTM_v1.nc','hAm',lati,loni,'con','m2');

figure
subplot(1,2,1)
pcolor(loni,lati,zi_tpx);
shading flat
title('TPXO9_atlas_v5.nc m2 hAm','interpreter','none')
caxis([0 0.27])

subplot(1,2,2)
pcolor(loni,lati,zi_arc);
shading flat
title('Arc2kmTM_v1.nc m2 hAm','interpreter','none')
caxis([0 0.27])
```
![tide_test](https://github.com/chadagreene/Tide-Model-Driver/assets/15901019/c19ebca8-2eae-4ee3-b265-23f6a556108e)

There's actually an `islatlon` test on line 72 of `tmd_interp`, which usually catches potential mixups in the order, but coincidentally in this particular example, all of the lat and lon values are within the possible range of values that could be associated with latitudes or longitudes.

### 2. Stripey gridded data in Arc2km

I am able to replicate the error, and this is only an issue of how `pcolor` tries to display a warped grid. Here's a comparison of displaying the same data with `pcolor` versus `scatter` (although scatter is slow, so watch out). 

```matlab 
filename = 'Arc2kmTM_v1.nc';

conid = 3;
variable = 'hRe';
[Z,lon,lat] = tmd_data(filename,variable,'geo');
ocean = tmd_data(filename,'mask'); 
data = Z(:,:,conid);
data(~ocean) = NaN; 

figure
subplot(1,2,1)
pcolor(lon,lat,data);
shading flat
hold on
xline(-66); xline(-62); yline(70); yline(72)  
xlim([-80 -50]); ylim([60 80])
title pcolor

subplot(1,2,2) 
scatter(lon(:),lat(:),5,data(:),'filled');
shading flat
hold on
xline(-66); xline(-62); yline(70); yline(72)  
xlim([-80 -50]); ylim([60 80])
title scatter
```
![tide_test3](https://github.com/chadagreene/Tide-Model-Driver/assets/15901019/5b353d02-4ffd-408f-afda-e91cbcc4d28d)

**Comment by lnferris** [comment]
My understanding is that this issue arises when data is not sorted with respect to x and y. Can you fix it by adding a line of code that sorts it?

**Comment by chadagreene** [comment]
@lnferris I'm afraid this is just the nature of map projections. The raw data comes on a regular grid in projected space. The `'geo'` option provides lat,lon coordinates corresponding to each pixel in the raw data grid, so by nature the outputs can't really be sorted. If a regular lat,lon grid is desired, the `tmd_interp` function can provide this sort of output.
