### ISSUE TITLE
References: in code but not paper

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#18]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

Snyder, J. P., 1982
Foreman, M. G. G., & Henry, R. F. (1989)

**Comment by chadagreene** [comment]
We've added a citation to Foreman 1989 to the paper. Snyder is a reference to a specific polar stereographic map projection, and doesn't really belong in the main paper where the JOSS guidelines state that the content should provide only a high-level overview.
