### ISSUE TITLE
Minor documentation questions

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#19]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

[pu,pf] = tmd_nodal(constituents,p,N): what are pu, pf?

tmd_ll2ps(lat,lon,SLAT,SLON,HEMI): allowed inputs (vector, array, etc.)?

tmd_harp(t,hc,constituents,p,N,ph,omega): physical units of input/outputs?

dh = tmd_InferMinor(hc,constituents,t,s,h,p,N): what is a "correction"?

tmd_astrol.m: why are there question marks on line 51?  Given there are several time formats within TMD stack code: days since Jan 1, 1992; days since Nov 17, 1858, and MATLAB datenum (days since 00-Jan-0000'); the "???" does not inspire user confidence.

**Comment by chadagreene** [comment]
We've made changes to the function headers to clarify some of the points above, but we should note: These functions are not user-facing, and should not be interacted with directly. Accordingly, the bar for documentation needs only to meet that of `stream3c` or any of the other hundreds of official MATLAB functions you'll find under the hood. 

And we agree, the mish-mash of time formats in some of the underlying functions is lousy coding practice and it's just begging to introduce errors (or at least erode confidence in the code, as you point out). However, these are the exact equations that have been employed in all previous versions of TMD and we felt it was best not to mess with them.

**Comment by lnferris** [comment]
These functions do not meet the bar for `stream3`, and the expectation for documentation of open-source software (including under-the-hood functions) is that which allows a future user to modify or contribute to software. This revision of TMD was presented as addressing prior clarity issues, one such being undocumented magic numbers  and lack of documentation in under-the-hood functions.

**Comment by lnferris** [comment]
For example, the outputs of `tmd_harp` says:
```
% Outpus: 
%    hhat: reconstructed tide (size Tx1).
```

The function body of `tmd_astrol` includes:

```
t_mjd = t - datenum(1992,1,1) + 48622;

% Convert time from UTC in decimal MJD to ???
T = t_mjd - 51544.4993;

% Mean longitude of moon:
s = 218.3164 + 13.17639648 * T;
```

**Comment by chadagreene** [comment]
Note, I was referencing `stream3c`, not `stream3`. 

These time conversions, including the corresponding comments, are the exact code that has been part of TMD for decades, and the conversions occur inside a function that users should never need to directly interact with. Our approach in this update to TMD has been to keep the exact calculations that have stood the test of time, but write the user-facing functions in such a way that users never have to think about the conversions.

**Comment by kthyng** [comment]
I understand @chadagreene's reasoning for not changing the code since part of the goal here is apparently to keep that the same over time. I don't see why you shouldn't add more documentation to make things clearer, especially when specifically requested. @lnferris's reasoning is good that that is part of the point of having open source code and there is an extra level of expectation when publishing open source code. The answers to the questions above could be notes in the function(s).

**Comment by chadagreene** [comment]
> [pu,pf] = tmd_nodal(constituents,p,N): what are pu, pf?

We have clarified "Nodal correction outputs pu,pf have units of radians and are are MxN dimensions, corresponding to M timesteps and N constituents."

> tmd_ll2ps(lat,lon,SLAT,SLON,HEMI): allowed inputs (vector, array, etc.)? 

Any input dimensions are allowed. By convention, we only specify dimension limitations when they are in fact limited, or when some meaningful insight can be gained through describing the dimensions. Neither is the case here, so we keep it unchanged. 

> tmd_harp(t,hc,constituents,p,N,ph,omega): physical units of input/outputs?

Output hhat is the reconstructed tide, as described in the function header, and has the same units accordingly. Input t is described in the function header as having datum units, hc contains the complex harmonic constants and will of course have whatever units the complex harmonic constants have, p is the lunar perigee, N is the lunar node, and phase is in radians as is consistent throughout the TMD3.0 package, and the units of omega are specified as s^-1 in the function header. 

> dh = tmd_InferMinor(hc,constituents,t,s,h,p,N): what is a "correction"?

This is a question about tide theory, and if the concept is not understood, then this does not feel like the appropriate place to provide such a lesson. The tmd_InterMinor function is not user-facing, and no one should ever need to open it or even call it directly. The only time anyone should ever need to open this function is if they wish to adapt it into something else, and we assume that anyone who is ever tasked with altering code for minor constituent corrections will understand what minor constituent corrections are. We have described what the function does in the header, we point users to Richard Ray's perth2 function that it is based on, and we described all of the changes we made to the code in this update. No further changes are warranted here.

> tmd_astrol.m: why are there question marks on line 51? Given there are several time formats within TMD stack code: days since Jan 1, 1992; days since Nov 17, 1858, and MATLAB datenum (days since 00-Jan-0000'); the "???" does not inspire user confidence.

The question marks are preserved intact from the legacy code that we have adapted, and we haven't touched the code or time formats, so it doesn't seem appropriate to erase the comments from previous coders.

**Comment by kthyng** [comment]
> We have clarified "Nodal correction outputs pu,pf have units of radians and are are MxN dimensions, corresponding to M timesteps and N constituents."

You have a typo in this section.

> Any input dimensions are allowed. By convention, we only specify dimension limitations when they are in fact limited, or when some meaningful insight can be gained through describing the dimensions. Neither is the case here, so we keep it unchanged.

Explicit is better than implicit and this has the potential to create confusion. Please update.

> Output hhat is the reconstructed tide, as described in the function header, and has the same units accordingly. Input t is described in the function header as having datum units, hc contains the complex harmonic constants and will of course have whatever units the complex harmonic constants have, p is the lunar perigee, N is the lunar node, and phase is in radians as is consistent throughout the TMD3.0 package, and the units of omega are specified as s^-1 in the function header.

Explicit is better than implicit. If you can write it out here to improve clarity, you can add it to the docs to improve clarity.

> This is a question about tide theory, and if the concept is not understood, then this does not feel like the appropriate place to provide such a lesson. The tmd_InterMinor function is not user-facing, and no one should ever need to open it or even call it directly. The only time anyone should ever need to open this function is if they wish to adapt it into something else, and we assume that anyone who is ever tasked with altering code for minor constituent corrections will understand what minor constituent corrections are. We have described what the function does in the header, we point users to Richard Ray's perth2 function that it is based on, and we described all of the changes we made to the code in this update. No further changes are warranted here.

You can still say something useful. For example: you can add to the docs that the function is not user facing but also be aware that users look at the code and add more detail to improve your codebase. Perhaps you can briefly summarize the correction or you can link to something that provides a longer explanation.

> The question marks are preserved intact from the legacy code that we have adapted, and we haven't touched the code or time formats, so it doesn't seem appropriate to erase the comments from previous coders.

This is your chance to improve the comments in the code. If you can figure out what the "???" should be, you should fix the comment.

**Comment by chadagreene** [comment]
> You have a typo in this section.

Fixed.

> Explicit is better than implicit and this has the potential to create confusion. Please update.

Done. 

> Explicit is better than implicit. If you can write it out here to improve clarity, you can add it to the docs to improve clarity.

Done. 

> You can still say something useful. For example: you can add to the docs that the function is not user facing but also be aware that users look at the code and add more detail to improve your codebase. Perhaps you can briefly summarize the correction or you can link to something that provides a longer explanation.

Perhaps it's best to let the original author of the code describe it in his own words. In the function header I've added the note that "tmd_InferMinor returns correction for 16 minor tidal constituents... This is based on Richard Ray's code perth2. For further description, see Ray, Richard D. "Global ocean tide models on the eve of TOPEX/POSEIDON." IEEE transactions on Geoscience and Remote Sensing 31.2 (1993): 355-364."

> This is your chance to improve the comments in the code. If you can figure out what the "???" should be, you should fix the comment.

I've removed the question marks.
