### ISSUE TITLE
TMD 2.5 to TMD 3.0 question

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#20]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018) and related to [Issue 11](https://github.com/chadagreene/Tide-Model-Driver/issues/11).

This is testing a function call (`tmd_extract_HC()`) used in a common tidal preparation for ROMS ([otps2frc_v5.m](https://www.myroms.org/hunter/roms_tides/update/otps/)). I get that `u_phase `and `uPh` are not pseudo-equivalent. Is there a units mismatch going on?

```
filename='/Users/lnferris/TMD_Matlab_Toolbox_v2.5-master/TMD/DATA/Model_tpxo7.2';
[z_amp,z_phase,Depth,conList]=tmd_extract_HC(filename,lat,lon,'z',[]);
[u_amp,u_phase,~,~]=tmd_extract_HC(filename,lat,lon,'u',[]);

con = 1; % m2 from conList
figure
subplot(3,2,1)
pcolor(lon,lat,squeeze(z_amp(con,:,:)));
shading flat
colorbar
subplot(3,2,2)
pcolor(lon,lat,squeeze(z_phase(con,:,:)));
shading flat
colorbar
subplot(3,2,3)
pcolor(lon,lat,Depth);
shading flat
colorbar
subplot(3,2,4)
pcolor(lon,lat,squeeze(u_amp(con,:,:))./100);  %cm/s to m/s
shading flat
colorbar
subplot(3,2,5)
pcolor(lon,lat,squeeze(u_phase(con,:,:))); 
shading flat
colorbar

%% TMD 3.0

addpath(genpath('/Users/lnferris/Desktop/Tide-Model-Driver-main'));
filename = '/Users/lnferris/Desktop/TPXO9_atlas_v5.nc';
conList = tmd_conlist(filename);
hAm = tmd_interp(filename,'hAm',lat,lon);
hPh = tmd_interp(filename,'hPh',lat,lon);
uAm = tmd_interp(filename,'uAm',lat,lon);
uPh = tmd_interp(filename,'uPh',lat,lon);
wct = tmd_interp(filename,'wct',lat,lon);

con = 4; % m2 from conList
figure
subplot(3,2,1)
pcolor(lon,lat,squeeze(hAm(:,:,con)));
shading flat
colorbar
subplot(3,2,2)
pcolor(lon,lat,squeeze(hPh(:,:,con)));
shading flat
colorbar
subplot(3,2,3)
pcolor(lon,lat,wct);
shading flat
colorbar
subplot(3,2,4)
pcolor(lon,lat,squeeze(uAm(:,:,con)));
shading flat
colorbar
subplot(3,2,5)
pcolor(lon,lat,squeeze(uPh(:,:,con)));
shading flat
colorbar
```

**Comment by lnferris** [comment]
Also this isn't an issue, but the TMD 3.0 code block is 3x faster; nice job.

**Comment by chadagreene** [comment]
@lnferris I don't have quite enough to replicate your code, and I'm not sure what difference you're seeing between the two results. Can you please upload the resulting figures or describe the differences you're seeing?

**Comment by kthyng** [comment]
@lnferris Can you respond here?

**Comment by lnferris** [comment]
[lat.csv](https://github.com/chadagreene/Tide-Model-Driver/files/13823087/lat.csv)
[lon.csv](https://github.com/chadagreene/Tide-Model-Driver/files/13823088/lon.csv)
![2 5](https://github.com/chadagreene/Tide-Model-Driver/assets/24570061/ad5c3565-da0a-4ab0-af11-24e039041178)
![3 0](https://github.com/chadagreene/Tide-Model-Driver/assets/24570061/e87b7d96-d3a6-4f52-944d-8cb531c2c06c)

**Comment by chadagreene** [comment]
Ahh, okay, so it's just a matter of radians vs degrees. I see now that I hadn't included the angle units in the documentation. 

I've just updated all the documentation to be clear that the angle units are radians. Thanks for catching this.

**Comment by lnferris** [comment]
Can you mention this in your [table](https://github.com/chadagreene/Tide-Model-Driver/blob/main/doc/whats_new.md) because a subtle units change has the potential to break people's tools? I agree that radians is better but had to dig to find this difference.

**Comment by lnferris** [comment]
@chadagreene you can close this issue **after editing the table,** I have nothing more on this issue.

**Comment by chadagreene** [comment]
Done.
