### ISSUE TITLE
TPXO9_atlas_v5_to_NetCDF.m error with fseek

### ISSUE THREAD

**Issue by AlekseiBuinyi** [chadagreene/Tide-Model-Driver#21]
Dear @chadagreene ,
I've got an issue with the script TPXO9_atlas_v5_to_NetCDF.m. 
Dr. Erofeeva has shared the atlas to me, but when I try the %% Load data part, I've got an error 

`Error using fseek
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in grd_in (line 8)
fseek(fid,4,'bof');
 `
Do you have any idea what happened and how to deal with it?

**Comment by chadagreene** [comment]
Hi @AlekseiBuinyi thanks for letting me know. I wonder if it's unable to find the file. Rather than wrestle with TPXO9_atlas_v5_to_NetCDF.m, it might be easiest just to email me and I think I can save you the trouble.

**Comment by AlekseiBuinyi** [comment]
Hello Dr. Greene,
I think I've solved a first stage of the issue. If I call the whole name of
.NC file, the script is able to read it. May be here the problem is in OS.
But I face some other issues further - an output of processed grid file is
empty.
Regards,
Aleksei

ср, 17 июл. 2024 г., 19:15 Chad A. Greene ***@***.***>:

**Comment by chadagreene** [comment]
I wonder if the `fid` identifiers got confused somewhere along the way. Just shoot me an email and we can discuss offline.
