### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#6]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

Please add guidance (even a quick sentence) in README.md providing instructions for bug fixes or contributions. Will you be using GitHub issues to track errors? What kind of contributions are you accepting, if any? Is Chad, Svetlana, or someone else the primary point of contact?

**Comment by chadagreene** [comment]
Good idea. I've added a section in the README on how to contribute. As for the personal point of contact, I've been careful not to encourage too many personal private communications bc in my experience that really encourages emails from strangers asking me to do their homework or research for them :-)
