### ISSUE TITLE
Suggestion: tmd_conlist

### ISSUE THREAD

**Issue by lnferris** [chadagreene/Tide-Model-Driver#9]
This is part of [JOSS review](https://github.com/openjournals/joss-reviews/issues/6018).

If you end the function with something like:

```
A = strings(length(conList),1);
for i = 1:length(conList)
    A(i) = conList{i};
end
conList = A;
```

It will give the user with a string array, which might be preferable to a cell array.

**Comment by chadagreene** [comment]
The suggested approach is reasonable, but we don't see any clear benefit of string arrays over cell arrays, and they're easy enough to convert back and forth, so we leave this one as is.
